language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get update

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../.install -DCMAKE_BUILD_TYPE=Debug $OPTIONS ..
  - cmake --build . --target install

branches:
  only:
    - master

os:
  - linux
