language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:pitti/systemd -y
  - sudo apt-get update

install:
  - sudo apt-get install libboost1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../.install -DCMAKE_BUILD_TYPE=Debug -DNGPOMMEDGUI_PID_FILE=$HOME/ngpommedgui.pid $OPTIONS ..
  - cmake --build . --target install

branches:
  only:
    - master

os:
  - linux
